version: '3.7'

services:
  db: 
    image: mongo:latest
    container_name: db
    restart: always
    volumes:
      - ./db_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - backend

  web:
    image: mongo-express
    container_name: db-gui
    restart: always
    depends_on:
      - db
    environment:
      ME_CONFIG_MONGODB_SERVER: db
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: root
    ports:
      - "8081:8081"
    networks:
      - backend
volumes:
  db_data: {}
networks:
  backend: